version: '2'
services:
  mysql:
      build: ./docker-configs/mysql
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: admin
      volumes:
        - ./data/mysql:/var/lib/mysql
        - ./data/init.d:/docker-entrypoint-initdb.d
  golang:
      build: ./docker-configs/golang
      ports:
        - "5000:5000"
      volumes:
        - ./go-apps:/go
      depends_on:
        - mysql
      links:
          - mysql
      tty: true
  node:
      build: ./docker-configs/node
      ports:
          - '8080:8080'
      volumes:
          - ./node-apps:/var/www
      links:
          - golang
      tty: true
